prefix_mode="#[bg=$red fg=$bg bold] P #[default]"
copy_mode="#[bg=$green fg=$bg bold] C #[default]"
normal_mode="#[bg=$blue fg=$bg bold] N #[default]"
mode="#{?client_prefix,$prefix_mode,#{?pane_in_mode,$copy_mode,$normal_mode}}"
