prefix_mode="#[bg=$red fg=$bg] PREFIX #[default]"
copy_mode="#[bg=$green fg=$bg] COPY #[default]"
normal_mode="#[bg=$blue fg=$bg] NORMAL #[default]"
mode="#{?client_prefix,$prefix_mode,#{?pane_in_mode,$copy_mode,$normal_mode}}"

session="#[fg=$magenta bold]󰕮 #S#[default]"
separator="#[fg=$muted]❯#[default]"

set -g status-position "top"
set -g status-style "bg=default"

set -g status-left "$mode $session $separator "
set -g status-left-length 50

set -g status-right "$cpu_usage $ram_usage"

set -g window-status-separator "  "
set -g window-status-current-format "#[fg=$blue bold]#I:#W"
set -g window-status-format "#[fg=$fg]#I:#W"
