right_divider=""
left_inverse_divider=""
divider=""

prefix_mode="#[bg=$red fg=$bg] PREFIX #[default]"
copy_mode="#[bg=$green fg=$bg] COPY #[default]"
normal_mode="#[bg=$blue fg=$bg] NORMAL #[default]"
mode="#{?client_prefix,$prefix_mode,#{?pane_in_mode,$copy_mode,$normal_mode}}"

session="#[bg=$magenta fg=$bg] 󰕮 #S #[bg=default fg=$magenta]$right_divider#[default]"

set -g status-position "top"
set -g status-style "bg=default"

set -g status-left "$mode$session"
set -g status-left-length 50

set -g status-right ""

set -g window-status-separator ""
set -g window-status-current-format "#[fg=$blue]$left_inverse_divider#[bg=$blue fg=$bg] #I #[bg=$muted fg=$blue]$right_divider #[fg=$fg]#W #[bg=default fg=$muted]$right_divider"
set -g window-status-format "#[fg=$dimmed]$left_inverse_divider#[bg=$dimmed fg=$fg] #I #[bg=$muted fg=$dimmed]$right_divider #[fg=$fg]#W #[bg=default fg=$muted]$right_divider"
