set -g status-position "top"
set -g status-style "bg=default fg=default"
set -g status-justify "absolute-centre"

set -g status-left "$mode$session "
set -g status-left-length 50

set -g status-right ""
set -g status-right-length 50

set -g window-status-separator "  "
set -g window-status-current-format "#[fg=$blue]#I #W"
set -g window-status-format "#[fg=$secondary_fg]#I #W"
