set -g mode-style "noattr bg=$selected_bg"

set -g message-style "fg=$cmd_fg bg=default"
set -g message-command-style "fg=$cmd_fg bg=default"

run -C "set -g prompt-cursor-colour '$fg'"

set -g pane-border-style "fg=$divider_fg"
set -g pane-active-border-style "fg=$blue"

set -g popup-border-style "fg=$divider_fg"

set -g display-panes-colour "$divider_fg"
set -g display-panes-active-colour "$divider_fg"
