set -g mode-style "bg=$muted fg=$fg"

set -g message-style "fg=$fg bg=$bg"
set -g message-command-style "fg=$fg bg=default"

set -g pane-border-style "fg=$muted"
set -g pane-active-border-style "fg=$blue"

set -g popup-border-style "fg=$muted"
