source ~/.config/tmux/palette.conf
source ~/.config/tmux/theme.conf
source ~/.config/tmux/statusbar.conf
source ~/.config/tmux/keybinds.conf
source ~/.config/tmux/search.conf

set -s escape-time 0
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5

set -g focus-events on
setw -g aggressive-resize on

set -g default-terminal 'tmux-256color'

set -g base-index 1

set -ga terminal-overrides ",*:Tc"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
